### ISSUE TITLE
[Bug]: Quark Matrix Enchanter Crashing

### ISSUE THREAD

**Issue by Reshirou** [someaddons/cursery#8]
### Describe the bug you're experiencing

Enchanting items seems to randomly cause crashes when you try to take your enchanted item.

### Reproducability

Just keep enchanting diamond swords; you'll eventually crash. When you load the world back up and try to take out that diamond sword again, you'll consistently keep crashing.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

https://gist.github.com/Reshirou/60256b00944a75bb9db90b022c5f74de

**Comment by someaddons** [comment]
Fixed

**Comment by Reshirou** [comment]
I dont know how to ask this without risking being annoying, but, do you have a 1.19.2 version waiting to be uploaded? Qaurk isnt on 1.19.3, so this cant exactly be considered fixed in the newest 1.19.3 exclusive release

**Comment by Lictor000** [comment]
Hi, I understand the issue should be fixed (trying with the single mods the issue does not happen) but in my custom modpack I am experiencing it again when I add this mod exactly as described by OP and very frequently. I tried to find out other possible mod conflicts messing with every mod that covers enchanting with no success.
Here a crash report https://pastebin.com/aAVe5rZt

Minecraft versoin: 1.19.2
Mod version: 3.1 (Forge)

Downgrading the mod to 3.0 the issue seems to disappear (on curseforge there's two 3.0 versions, I tried the one marked with the quark compat fix in the changelog).
